LANGUAGES = [
    {"code": "en", "name": "English"},
    {"code": "fa", "name": "Persian"},
    {"code": "es", "name": "Spanish"},
    {"code": "fr", "name": "French"},
    {"code": "de", "name": "German"},
    {"code": "it", "name": "Italian"},
    {"code": "pt", "name": "Portuguese"},
    {"code": "ru", "name": "Russian"},
    {"code": "ar", "name": "Arabic"},
    {"code": "tr", "name": "Turkish"},
    {"code": "zh", "name": "Chinese"},
    {"code": "ja", "name": "Japanese"},
    {"code": "ko", "name": "Korean"},
    {"code": "hi", "name": "Hindi"},
    {"code": "ur", "name": "Urdu"},
    {"code": "bn", "name": "Bengali"},
    {"code": "nl", "name": "Dutch"},
    {"code": "sv", "name": "Swedish"},
    {"code": "pl", "name": "Polish"},
    {"code": "uk", "name": "Ukrainian"},
    {"code": "ro", "name": "Romanian"},
    {"code": "el", "name": "Greek"},
    {"code": "he", "name": "Hebrew"},
    {"code": "th", "name": "Thai"},
    {"code": "vi", "name": "Vietnamese"},
    {"code": "id", "name": "Indonesian"},
    {"code": "ms", "name": "Malay"},
    {"code": "ta", "name": "Tamil"},
    {"code": "te", "name": "Telugu"},
    {"code": "ml", "name": "Malayalam"},
    {"code": "mr", "name": "Marathi"},
    {"code": "pa", "name": "Punjabi"},
    {"code": "sw", "name": "Swahili"},
    {"code": "zu", "name": "Zulu"},
    # Additional languages
    {"code": "af", "name": "Afrikaans"},
    {"code": "sq", "name": "Albanian"},
    {"code": "am", "name": "Amharic"},
    {"code": "hy", "name": "Armenian"},
    {"code": "az", "name": "Azerbaijani"},
    {"code": "eu", "name": "Basque"},
    {"code": "be", "name": "Belarusian"},
    {"code": "bs", "name": "Bosnian"},
    {"code": "bg", "name": "Bulgarian"},
    {"code": "ca", "name": "Catalan"},
    {"code": "ceb", "name": "Cebuano"},
    {"code": "ny", "name": "Chichewa"},
    {"code": "co", "name": "Corsican"},
    {"code": "hr", "name": "Croatian"},
    {"code": "cs", "name": "Czech"},
    {"code": "da", "name": "Danish"},
    {"code": "eo", "name": "Esperanto"},
    {"code": "et", "name": "Estonian"},
    {"code": "tl", "name": "Filipino"},
    {"code": "fi", "name": "Finnish"},
    {"code": "fy", "name": "Frisian"},
    {"code": "gl", "name": "Galician"},
    {"code": "ka", "name": "Georgian"},
    {"code": "gu", "name": "Gujarati"},
    {"code": "ht", "name": "Haitian Creole"},
    {"code": "ha", "name": "Hausa"},
    {"code": "haw", "name": "Hawaiian"},
    {"code": "hmn", "name": "Hmong"},
    {"code": "hu", "name": "Hungarian"},
    {"code": "is", "name": "Icelandic"},
    {"code": "ig", "name": "Igbo"},
    {"code": "ga", "name": "Irish"},
    {"code": "jw", "name": "Javanese"},
    {"code": "kn", "name": "Kannada"},
    {"code": "kk", "name": "Kazakh"},
    {"code": "km", "name": "Khmer"},
    {"code": "rw", "name": "Kinyarwanda"},
    {"code": "ky", "name": "Kyrgyz"},
    {"code": "lo", "name": "Lao"},
    {"code": "la", "name": "Latin"},
    {"code": "lv", "name": "Latvian"},
    {"code": "lt", "name": "Lithuanian"},
    {"code": "lb", "name": "Luxembourgish"},
    {"code": "mk", "name": "Macedonian"},
    {"code": "mg", "name": "Malagasy"},
    {"code": "mt", "name": "Maltese"},
    {"code": "mi", "name": "Maori"},
    {"code": "mn", "name": "Mongolian"},
    {"code": "my", "name": "Myanmar (Burmese)"},
    {"code": "ne", "name": "Nepali"},
    {"code": "no", "name": "Norwegian"},
    {"code": "ps", "name": "Pashto"},
    # {"code": "fa", "name": "Persian"},  # Already in list
    # {"code": "pl", "name": "Polish"},  # Already in list
    # {"code": "pt", "name": "Portuguese"},  # Already in list
    # {"code": "pa", "name": "Punjabi"},  # Already in list
    # {"code": "ro", "name": "Romanian"},  # Already in list
    {"code": "sm", "name": "Samoan"},
    {"code": "gd", "name": "Scots Gaelic"},
    {"code": "sr", "name": "Serbian"},
    {"code": "st", "name": "Sesotho"},
    {"code": "sn", "name": "Shona"},
    {"code": "sd", "name": "Sindhi"},
    {"code": "si", "name": "Sinhala"},
    {"code": "sk", "name": "Slovak"},
    {"code": "sl", "name": "Slovenian"},
    {"code": "so", "name": "Somali"},
    {"code": "su", "name": "Sundanese"},
    {"code": "tg", "name": "Tajik"},
    {"code": "tt", "name": "Tatar"},
    {"code": "cy", "name": "Welsh"},
    {"code": "xh", "name": "Xhosa"},
    {"code": "yi", "name": "Yiddish"},
    {"code": "yo", "name": "Yoruba"},
    # {"code": "zu", "name": "Zulu"},  # Already in list
    # Adding some more with 3-letter codes
    {"code": "ast", "name": "Asturian"},
    {"code": "bal", "name": "Baluchi"},
    {"code": "bho", "name": "Bhojpuri"},
    {"code": "brx", "name": "Bodo"},
    {"code": "bre", "name": "Breton"},
    {"code": "chq", "name": "Chinantec"},
    {"code": "div", "name": "Dhivehi"},
    {"code": "doi", "name": "Dogri"},
    {"code": "dyu", "name": "Dyula"},
    {"code": "fuv", "name": "Fulfulde"},
    {"code": "gom", "name": "Goan Konkani"},
    {"code": "grn", "name": "Guarani"},
    # {"code": "hin", "name": "Hindi"},  # Already have 'hi'
    {"code": "iku", "name": "Inuktitut"},
    {"code": "kbd", "name": "Kabardian"},
    {"code": "kab", "name": "Kabyle"},
    {"code": "kal", "name": "Kalaallisut"},
    # {"code": "kan", "name": "Kannada"},  # Already have 'kn'
    {"code": "kur", "name": "Kurdish"},
    {"code": "lim", "name": "Limburgish"},
    {"code": "lug", "name": "Ganda"},
    {"code": "luo", "name": "Luo"},
    {"code": "lus", "name": "Mizo"},
    {"code": "nds", "name": "Low German"},
    # {"code": "nep", "name": "Nepali"},  # Already have 'ne'
    {"code": "orm", "name": "Oromo"},
    {"code": "oss", "name": "Ossetian"},
    {"code": "pam", "name": "Pampanga"},
    {"code": "que", "name": "Quechua"},
    {"code": "srd", "name": "Sardinian"},
    {"code": "tuk", "name": "Turkmen"},
    {"code": "twi", "name": "Twi"},
    {"code": "umb", "name": "Umbundu"},
    {"code": "wol", "name": "Wolof"},
    {"code": "zza", "name": "Zaza"},
]