# Generated by Django 4.2.7 on 2026-02-14 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LFG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_cross_play', models.BooleanField(default=False)),
                ('mic_enabled', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('bumped_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lfgs', to='games.game')),
                ('game_mode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.gamemode')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lfg', to=settings.AUTH_USER_MODEL)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.platform')),
            ],
        ),
        migrations.CreateModel(
            name='LFGStatImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='lfg/stats/')),
                ('lfg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stat_images', to='posts.lfg')),
            ],
        ),
        migrations.CreateModel(
            name='LFGSelectedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_category_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.gamecategoryitem')),
                ('lfg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_items', to='posts.lfg')),
            ],
            options={
                'unique_together': {('lfg', 'game_category_item')},
            },
        ),
    ]
