name: Deploy Frontend
on:
  push:
    branches:
      - main
      - dev
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: |
          cd /root/project/Frontend
          git pull origin dev
          npm install
          npm run build
          pm2 restart frontend

          
            